### ISSUE TITLE
Hardware:  Adjusting the T-Glass display

### ISSUE THREAD

**Issue by JpEncausse** [Xinyuan-LilyGO/LilyGO-T-Wristband-and-T-Glass#2]
Hello,
I just received the T-Glass and need to validate the Prism location.
- Putting the T-Glass like explained on Lilygo.com (on the right, switch down) the display must be VERY FAR to be correct but small
- Looking at the glass the opposite way the display is closer and seems more usable

Right Side (very far to get the focus)
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-Wristband-and-T-Glass/assets/1140867/53ebc2c5-6aa6-4ca7-a896-987607cf9398)

Left Side (not perfect but more usable)
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-Wristband-and-T-Glass/assets/1140867/669c65f0-c027-4955-a49f-810d306d8ecd)

I remember GoogleGLass +10 years ago the display was close and zoom like the Photo 2 so I was wondering if the current mount is OK or if it should be turn around ? ANd if yes, how ?

**Comment by quadjojo** [comment]
Hey!
Got my T-Glass today and was wondering the same thing.
Impossible for me to see a sharp picture when in Photo1 orientation.

**Comment by JpEncausse** [comment]
Right Side seem to be the default way but need to be very far from eye. It's like looking at a display 1:1 I don't understand the usecase. It's like hanging a screen.

If you rotate the prism and change the code of the display you have a closer view with less luminosity and many test&learn to find the sweet spot like Google Glass. But it feel more XR Glass.

**Comment by criegit** [comment]
Hi,

Is there any solution to fix the glasses? I was ultra happy when the parcel shipped so quickly. But after the first test this is completely useless to me.
Regular direction: I can't even focus at furthest distance. (i wear regular glasses) I hoped to be able to focus almost to infinity.
Reverse direction as mentioned above: very small FOV and almost impossible to see, even in a slightly darkened room.


Is there any way to fix this?

**Comment by smithjacobj** [comment]
Got mine today and was confused too.

It seems like the way they have it mounted we're looking at it in un-magnified direct reflection in the prism, whereas this prism appears to be a "birdbath" (?) prism (I haven't found this language anywhere else so the terminology might be different) and should be double-boucing for good focal length (fig. C): 
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-Wristband-and-T-Glass/assets/3700215/c005f0ec-1403-4d5f-9682-26cffa76a214)

https://sid.onlinelibrary.wiley.com/doi/full/10.1002/msid.1226

**Comment by smithjacobj** [comment]
If you don't mind taking things apart, the combiner prism is installed with a little silicone band and can be slipped out when the cover is removed, rotated, then reinstalled. Clearly you'll have to mirror the image on the display to get the correct orientation, but it gets the right side of the combiner.

Even for just the prism this device is cheap. Single-unit combiner prisms are like $500 wherever I can find them.

**Comment by smithjacobj** [comment]
Still trying to figure out how to flip the view with the included hardware. Setting the driver's vertical flip bit doesn't work with the display. LVGL has limited software options, so I might have to manually do it.

**Comment by Izaic** [comment]
I think lilygo might have pulled the product because it's now explicitly unavailable everywhere, not just "out of stock". If that is infact the case, perhaps this issue is the reason why?

**Comment by criegit** [comment]
I really hope that they find a fix and i would be willing to test it. (I am not a big programmer, more a hardware guy)
3d printer is available and workshop as well.

I think there is quite a market for such a device, but it needs to be bright enough and best would be to have adjustable focus. I, for example need the focus near infinity.

**Comment by ossafe** [comment]
Just got mine and, well ... that's real disappointing.

**Comment by JpEncausse** [comment]
@smithjacobj did you find some prism exemple on Aliexpress ? I'm looking for spec exemples

Looking at Google Glass (2013) I think this is what everyone expect. The prism look the same but like you explain the reflexion is way different. 500$ seems a lot I wondering if there is some alternatives.
![image](https://github.com/Xinyuan-LilyGO/LilyGO-T-Wristband-and-T-Glass/assets/1140867/be0d1c57-7059-47cc-ac77-6a9cd9929766)

**Comment by smithjacobj** [comment]
@JpEncausse I'm having trouble finding just the prisms again. These are mostly full displays, including a waveguide option.
https://www.aliexpress.us/item/3256805265783262.html
https://www.aliexpress.us/item/3256806300295194.html
https://www.aliexpress.us/item/3256806474568059.html
https://www.aliexpress.us/item/3256806095139269.html
https://www.aliexpress.us/item/3256805177095886.html

**Comment by khaderm** [comment]
How has there been no care to update the community on what the status of these request are? There are a few incoming requests but nothing from the team?

**Comment by Ruelvillu** [comment]
> @JpEncausse I'm having trouble finding just the prisms again. These are mostly full displays, including a waveguide option. https://www.aliexpress.us/item/3256805265783262.html https://www.aliexpress.us/item/3256806300295194.html https://www.aliexpress.us/item/3256806474568059.html https://www.aliexpress.us/item/3256806095139269.html https://www.aliexpress.us/item/3256805177095886.html

i figured this out too, the only use able way to use it is a flipped prism, but they coated the wrong angle, making it appear as if its got this tile pattern, i dont even notice it now, but to fix your image flipping issue, i belive the solution i had was that the code is using reversed variables, also the code to make a usable tile that doesnt randomly light up other parts of the big rectangle screen has become really difficult to do, lots of times vs code decides to throw me rando errors but then ends up compiling and then failing lmao. lots of trial and error with this board and prism combo.

**Comment by Ruelvillu** [comment]
> > @JpEncausse I'm having trouble finding just the prisms again. These are mostly full displays, including a waveguide option. https://www.aliexpress.us/item/3256805265783262.html https://www.aliexpress.us/item/3256806300295194.html https://www.aliexpress.us/item/3256806474568059.html https://www.aliexpress.us/item/3256806095139269.html https://www.aliexpress.us/item/3256805177095886.html
> 
> i figured this out too, the only use able way to use it is a flipped prism, but they coated the wrong angle, making it appear as if its got this tile pattern, i dont even notice it now, but to fix your image flipping issue, i belive the solution i had was that the code is using reversed variables, also the code to make a usable tile that doesnt randomly light up other parts of the big rectangle screen has become really difficult to do, lots of times vs code decides to throw me rando errors but then ends up compiling and then failing lmao. lots of trial and error with this board and prism combo.

in the end i just flipped the side to my left, not needing to recode

**Comment by Ruelvillu** [comment]
> > > @JpEncausse I'm having trouble finding just the prisms again. These are mostly full displays, including a waveguide option. https://www.aliexpress.us/item/3256805265783262.html https://www.aliexpress.us/item/3256806300295194.html https://www.aliexpress.us/item/3256806474568059.html https://www.aliexpress.us/item/3256806095139269.html https://www.aliexpress.us/item/3256805177095886.html
> > 
> > 
> > i figured this out too, the only use able way to use it is a flipped prism, but they coated the wrong angle, making it appear as if its got this tile pattern, i dont even notice it now, but to fix your image flipping issue, i belive the solution i had was that the code is using reversed variables, also the code to make a usable tile that doesnt randomly light up other parts of the big rectangle screen has become really difficult to do, lots of times vs code decides to throw me rando errors but then ends up compiling and then failing lmao. lots of trial and error with this board and prism combo.
> 
> in the end i just flipped the side to my left, not needing to recode

it also helps to either print some better mounts so that the whole prism is sitting perfectly to the iris of your eye, i have used foam and tape untill my 3d printer gets here. i will post on my git the files for the mounts, and if you also want i will post my code too

**Comment by khaderm** [comment]
> If you don't mind taking things apart, the combiner prism is installed with a little silicone band and can be slipped out when the cover is removed, rotated, then reinstalled. Clearly you'll have to mirror the image on the display to get the correct orientation, but it gets the right side of the combiner.
> 
> Even for just the prism this device is cheap. Single-unit combiner prisms are like $500 wherever I can find them.

This works well. You can also make adjustments to the font size to fit more text on the display as the flipped prism shows less text. It is a pretty simple fix. Thanks for sharing.

**Comment by khaderm** [comment]
> > > @JpEncausse I'm having trouble finding just the prisms again. These are mostly full displays, including a waveguide option. https://www.aliexpress.us/item/3256805265783262.html https://www.aliexpress.us/item/3256806300295194.html https://www.aliexpress.us/item/3256806474568059.html https://www.aliexpress.us/item/3256806095139269.html https://www.aliexpress.us/item/3256805177095886.html
> > 
> > 
> > i figured this out too, the only use able way to use it is a flipped prism, but they coated the wrong angle, making it appear as if its got this tile pattern, i dont even notice it now, but to fix your image flipping issue, i belive the solution i had was that the code is using reversed variables, also the code to make a usable tile that doesnt randomly light up other parts of the big rectangle screen has become really difficult to do, lots of times vs code decides to throw me rando errors but then ends up compiling and then failing lmao. lots of trial and error with this board and prism combo.
> 
> in the end i just flipped the side to my left, not needing to recode

What font size do you recommend to get the most out of the screen real estate?

**Comment by fadiaburaid** [comment]
> @JpEncausse I'm having trouble finding just the prisms again. These are mostly full displays, including a waveguide option. https://www.aliexpress.us/item/3256805265783262.html https://www.aliexpress.us/item/3256806300295194.html https://www.aliexpress.us/item/3256806474568059.html https://www.aliexpress.us/item/3256806095139269.html https://www.aliexpress.us/item/3256805177095886.html

Here you go
https://www.aliexpress.us/item/1005007415787555.html

**Comment by JpEncausse** [comment]
> Here you go https://www.aliexpress.us/item/1005007415787555.html

Thanks, what are the capabilities of this prism ?
- Is it something like the GoogleGlass to see a bright image closer. Dids you test it on T-Glass ?
- or Is it the prism used by T-Glass that doesn't work ?

**Comment by fadiaburaid** [comment]
> > Here you go https://www.aliexpress.us/item/1005007415787555.html
> 
> Thanks, what are the capabilities of this prism ?
> 
> * Is it something like the GoogleGlass to see a bright image closer. Dids you test it on T-Glass ?
> * or Is it the prism used by T-Glass that doesn't work ?

I don't think the prism will solve the problem. I think a lens is needed to change the focal length.
After seeing the issues with T-glass. I looked for the prism to make my own glass but I didn't try it yet.

**Comment by JpEncausse** [comment]
> > > Here you go https://www.aliexpress.us/item/1005007415787555.html
> > 
> > 
> > Thanks, what are the capabilities of this prism ?
> > 
> > * Is it something like the GoogleGlass to see a bright image closer. Dids you test it on T-Glass ?
> > * or Is it the prism used by T-Glass that doesn't work ?
> 
> I don't think the prism will solve the problem. I think a lens is needed to change the focal length. After seeing the issues with T-glass. I looked for the prism to make my own glass but I didn't try it yet.

The current prism on the T-Glass "kind of" magnify the image:
- In regular position the luminosity is good but the image is not magnified
- In reverse position the luminosity is bad but the image is magnified

The problem is that the focal is too strong (too magnified) and lost brightness because of the way it do the focal if I correctly understand. If I remember, 10 years ago, on GoogleGlass the brighness and focal were good.

@Ruelvillu can you explain how you flip the prism ? Or the code ? How is it good ?

**Comment by smithjacobj** [comment]
> The problem is that the focal is too strong (too magnified) and lost brightness because of the way it do the focal if I correctly understand. If I remember, 10 years ago, on GoogleGlass the brighness and focal were good.

I was reading around and it seems Google Glass specifically used a polarized filter instead of simply a % filter.

**Comment by LilyGO** [comment]
Sorry, we have verified some issues about T-Galss.
1. Since the low-cost solution uses AMOLED, when using AMOLED, the display effect on the prism amplification surface will be pixel amplification. Typically, the magnified surface of a prism is used to display content, which requires a high-cost solution using Micro LED screens. This kind of screen has ultra-high resolution and can display good picture quality directly through prism amplification. In addition, the screen driver needs to select a chip platform that can support driving high resolution, so the difficulty and cost of programming are also different.
2. Our current version is indeed designed for long-distance use. Of course, if it is too far away from the eyes, there will be problems with the user experience.
3. Solution Now we have redesigned a version of the shell structure that is closer to the eyes, but it cannot avoid the display problems and pixel amplification problems mentioned above. If necessary, you can download the 3D printing file and reassemble it after downloading. During assembly, flip the prism to the magnified display surface. We will also publish corresponding tutorial videos. At the same time, the corresponding 3D printed shell kit is also available.

**Comment by criegit** [comment]
Thank you for the reply. I will try your solution when i have the time. 
Unfortunately i do not see too much applications currently.

Please stay on this topic and maybe there is a better solution in a few years.

**Comment by JpEncausse** [comment]
@criegit @LilyGO thanks for this workaround, I'll give a try when I'll have some time. An upside down sample would be great. Yes the luminosity is low but it could be usable for demo.

Maybe you should also look at TranscribGlass (CES2024) and some other statup that are working on glasses unders 100$

**Comment by ericlinagora** [comment]
> Sorry, we have verified some issues about T-Galss.

Come on lilygo, we knew we were taking a risk on a prototype, but you made a box and sourced stuff and all, how did you not know this and tell us beforehand ? What is this about "oh yeah it's not meant to be worn on glasses but held at a distance", how do you figure this is not deceptive marketing ? Can't you find a way to make it right by us investors who gave you money taking a risk ?
