### ISSUE TITLE
Updated Shell .stl files

### ISSUE THREAD

**Issue by Jaeder42** [Xinyuan-LilyGO/LilyGO-T-Wristband-and-T-Glass#3]
Hello I would like to customize some parts of the V2 glasses, but the provided .stl files are for the V1
Any chance of getting the updated files provided? 

Thanks in advance!

**Comment by ellisgl** [comment]
"T-Glass has two versions, the initial preview version and T-GlassV2 version (modified prism reflection method). The difference between the two is only the display method, the hardware is the same"

**Comment by Jaeder42** [comment]
They are very different in the housings

**Comment by lewisxhe** [comment]
Already added

**Comment by Jaeder42** [comment]
Thank you!
