### ISSUE TITLE
Looking for microphone audio format

### ISSUE THREAD

**Issue by 1Jamie** [Xinyuan-LilyGO/LilyGO-T-Wristband-and-T-Glass#6]
When using amoled.startmicrophone and grabbing audio from it, what format, samplerate and codec is the audio using? 

I am trying to take audio from the t-glass and send it over to a speech to text server and then send back the transcription to display but I am unable to ascertain the formatting to properly reformat to the models desired setup.

**Comment by lewisxhe** [comment]
PDM format [SPM1423HM4H-B](https://atta.szlcsc.com/upload/public/pdf/source/20240130/9456935DD33C1287F357EAD13123EBD9.pdf?Expires=4070880000&OSSAccessKeyId=LTAIJDIkh7KmGS1H&Signature=2kfQUaeGTgivj%2BWnnK5dFG8jCr4%3D&response-content-disposition=attachment%3Bfilename%3DC3171731_MEMS%25E9%25BA%25A6%25E5%2585%258B%25E9%25A3%258E_SPM1423HM4H-B_%25E8%25A7%2584%25E6%25A0%25BC%25E4%25B9%25A6_WJ1053583.PDF) microphone, default left alignment

![image](https://github.com/user-attachments/assets/754974c8-e600-4f01-8993-cc2c03652c8c)
![image](https://github.com/user-attachments/assets/c850ce3e-7b44-4f84-99eb-85b803438d05)

**Comment by 1Jamie** [comment]
That did the trick, thank you very much for the information. I was able to get speech to text working and displaying on the t-glass thanks to this info.

**Comment by DomoMKT** [comment]
you can find detailed information on the format, sample rate, and codec used by amoled.startmicrophone at [www.nemesyslabs.com](https://www.nemesyslabs.com).
